export const OPEN_MODAL = "OPEN_MODAL"
export const CLOSE_MODAL = "CLOSE_MODAL"
export const SET_PAGE_LIMIT = "SET_PAGE_LIMIT"
export const SET_PAGE_OFFSET = "SET_PAGE_OFFSET"
export const SET_EDIT_BUTTON = "SET_EDIT_BUTTON"
export const ENABLE_EDIT_BUTTON= 'ENABLE_EDIT_BUTTON'
export const DISABLE_EDIT_BUTTON = "DISABLE_EDIT_BUTTON"
export const SET_ROUTE_BUTTON= "SET_ROUTE_BUTTON"